import 'package:wonder_souls/src/features/trips/model/trip.dart';

class PublicTripsData {
  PublicTripsData._();

  static List<TripData> getCuratedPublicTrips() {
    final now = DateTime.now();
    return [
      TripData(
        id: "public_trip_tokyo_01",
        name: "Tokyo Explorer & Food Safari",
        description: "5 days exploring futuristic skyscrapers, ancient shrines, Shibuya crossing, Tsukiji sushi market, and vibrant Akihabara culture.",
        flag: "🇯🇵",
        dateRange: "5 Days · Mar - Apr",
        tripType: "Solo",
        category: "Balanced",
        imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200",
        startDate: now.add(const Duration(days: 14)),
        endDate: now.add(const Duration(days: 19)),
        mainDestination: "Tokyo",
        travelTastes: ["Food & Culinary", "Culture", "Photography", "Landmarks"],
        totalBudget: 1850.0,
        currency: "USD",
        transportBudget: 400.0,
        accommodationBudget: 750.0,
        foodBudget: 450.0,
        activitiesBudget: 250.0,
      ),
      TripData(
        id: "public_trip_paris_02",
        name: "Parisian Romance & Art Discovery",
        description: "6 enchanting days strolling through Montmartre, the Louvre museum, iconic Eiffel Tower sunset dinners, and charming Seine river cruises.",
        flag: "🇫🇷",
        dateRange: "6 Days · May - Jun",
        tripType: "Couple",
        category: "Luxury",
        imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200",
        startDate: now.add(const Duration(days: 30)),
        endDate: now.add(const Duration(days: 36)),
        mainDestination: "Paris",
        travelTastes: ["Romance", "Art & Museums", "Fine Dining", "History"],
        totalBudget: 2600.0,
        currency: "EUR",
        transportBudget: 500.0,
        accommodationBudget: 1200.0,
        foodBudget: 600.0,
        activitiesBudget: 300.0,
      ),
      TripData(
        id: "public_trip_bali_03",
        name: "Bali Island Tropical Retreat",
        description: "7 days of lush Ubud rice terraces, sacred waterfalls, sunset cliffside temples in Uluwatu, and relaxing beachfront surf vibes in Canggu.",
        flag: "🇮🇩",
        dateRange: "7 Days · Jul - Aug",
        tripType: "Friends",
        category: "Cheap",
        imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200",
        startDate: now.add(const Duration(days: 45)),
        endDate: now.add(const Duration(days: 52)),
        mainDestination: "Bali",
        travelTastes: ["Beaches", "Wellness & Yoga", "Nature & Wildlife", "Adventure"],
        totalBudget: 1100.0,
        currency: "USD",
        transportBudget: 200.0,
        accommodationBudget: 450.0,
        foodBudget: 250.0,
        activitiesBudget: 200.0,
      ),
      TripData(
        id: "public_trip_rome_04",
        name: "Rome: The Eternal City Tour",
        description: "4 days wandering through the Colosseum, Roman Forum, Vatican City, Trevi Fountain gelato stops, and authentic Trastevere trattorias.",
        flag: "🇮🇹",
        dateRange: "4 Days · Sep - Oct",
        tripType: "Family",
        category: "Balanced",
        imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200",
        startDate: now.add(const Duration(days: 60)),
        endDate: now.add(const Duration(days: 64)),
        mainDestination: "Rome",
        travelTastes: ["History", "Architecture", "Food & Wine", "Landmarks"],
        totalBudget: 1600.0,
        currency: "EUR",
        transportBudget: 300.0,
        accommodationBudget: 700.0,
        foodBudget: 400.0,
        activitiesBudget: 200.0,
      ),
      TripData(
        id: "public_trip_swiss_05",
        name: "Swiss Alps & Lakes Expedition",
        description: "6 days of panoramic alpine trains, breathtaking Zermatt Matterhorn views, Lucerne crystal lake cruises, and serene mountain villages.",
        flag: "🇨🇭",
        dateRange: "6 Days · Year-round",
        tripType: "Couple",
        category: "Luxury",
        imageUrl: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=1200",
        startDate: now.add(const Duration(days: 75)),
        endDate: now.add(const Duration(days: 81)),
        mainDestination: "Switzerland",
        travelTastes: ["Nature", "Hiking", "Mountains", "Scenic Trains"],
        totalBudget: 3400.0,
        currency: "CHF",
        transportBudget: 800.0,
        accommodationBudget: 1600.0,
        foodBudget: 600.0,
        activitiesBudget: 400.0,
      ),
      TripData(
        id: "public_trip_dubai_06",
        name: "Dubai Skyline & Desert Wonder",
        description: "4 days experiencing Burj Khalifa heights, desert sunset dune safaris with Bedouin dinners, Dubai Mall aquariums, and luxury marina yachting.",
        flag: "🇦🇪",
        dateRange: "4 Days · Nov - Feb",
        tripType: "Friends",
        category: "Luxury",
        imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200",
        startDate: now.add(const Duration(days: 90)),
        endDate: now.add(const Duration(days: 94)),
        mainDestination: "Dubai",
        travelTastes: ["Luxury", "Shopping", "Desert Safari", "Nightlife"],
        totalBudget: 2200.0,
        currency: "USD",
        transportBudget: 400.0,
        accommodationBudget: 1000.0,
        foodBudget: 500.0,
        activitiesBudget: 300.0,
      ),
    ];
  }
}
